import {GridsterConfigS} from './GridsterConfigS.interface';
// import {GridsterEmptyCell} from './gridsterEmptyCell.service';
// import {GridsterCompact} from './gridsterCompact.service';
import {GridsterConfig} from './GridsterConfig.interface';
import {GridsterItemInterface} from './GridsterItem.interface';
import {GridsterItemComponentInterface} from './GridsterItemComponent.interface';
import {GridsterRenderer} from './GridsterRenderer';
import { Renderer } from './utils/renderer';

export abstract class GridsterComponentInterface {
  $options: GridsterConfigS;
  grid: Array<GridsterItemComponentInterface>;
  checkCollision: (item: GridsterItemInterface) => GridsterItemComponentInterface | boolean;
  checkCollisionForSwaping: (item: GridsterItemInterface) => GridsterItemComponentInterface | boolean;
  positionXToPixels: (x: number) => number;
  pixelsToPositionX: (x: number, roundingMethod: (x: number) => number, noLimit?: boolean) => number;
  positionYToPixels: (y: number) => number;
  pixelsToPositionY: (y: number, roundingMethod: (x: number) => number, noLimit?: boolean) => number;
  findItemWithItem: (item: GridsterItemInterface) => GridsterItemComponentInterface | boolean;
  findItemsWithItem: (item: GridsterItemInterface) => Array<GridsterItemComponentInterface>;
  checkGridCollision: (item: GridsterItemInterface) => boolean;
  el: any;
  renderer: Renderer;
  gridRenderer: GridsterRenderer;
  options: GridsterConfig;
  calculateLayoutDebounce: () => void;
  updateGrid: () => void;
  movingItem: GridsterItemInterface | null;
  addItem: (item: GridsterItemComponentInterface) => void;
  removeItem: (item: GridsterItemComponentInterface) => void;
  previewStyle: (drag?: boolean) => void;
  mobile: boolean;
  curWidth: number;
  curHeight: number;
  columns: number;
  rows: number;
  curColWidth: number;
  curRowHeight: number;
  windowResize: (() => void) | null;
  setGridDimensions: (() => void);
  dragInProgress: boolean;
  // emptyCell: GridsterEmptyCell;
  // compact: GridsterCompact;
  gridRows: Array<number>;
  gridColumns: Array<number>;
}
